targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            "^lib/models/{{}}.dart": "lib/models/generated/{{}}.g.dart"
            "^lib/providers/{{}}.dart": "lib/providers/generated/{{}}.g.dart"
      freezed:
        generate_for:
          include:
            - lib/models/*.dart
        options:
          build_extensions:
            "^lib/models/{{}}.dart": "lib/models/generated/{{}}.freezed.dart"
      json_serializable:
        generate_for:
          include:
            - lib/models/*.dart
        options:
          field_rename: snake
          explicit_to_json: true
          include_if_null: true
      riverpod_generator:
        generate_for:
          include:
            - lib/providers/*.dart
        options:
          build_extensions:
            "^lib/providers/{{}}.dart": "lib/providers/generated/{{}}.g.dart"
          provider_name_suffix: "Provider"
