targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/models/*.dart
            - lib/providers/*.dart
            - lib/services/*.dart
        options:
          build_extensions:
            "^lib/models/{{}}.dart": "lib/models/generated/{{}}.freezed.dart"
            "^lib/providers/{{}}.dart": "lib/providers/generated/{{}}.freezed.dart"
            "^lib/services/{{}}.dart": "lib/services/generated/{{}}.freezed.dart"

      json_serializable:
        generate_for:
          include:
            - lib/models/*.dart
            - lib/providers/*.dart
            - lib/services/*.dart
        options:
          field_rename: snake
          explicit_to_json: true
          include_if_null: true

      riverpod_generator:
        generate_for:
          include:
            - lib/providers/*.dart
        options:
          build_extensions:
            "^lib/providers/{{}}.dart": "lib/providers/generated/{{}}.g.dart"
          provider_name_suffix: "Provider"

      source_gen|combining_builder:
        options:
          build_extensions:
            "^lib/models/{{}}.dart": "lib/models/generated/{{}}.g.dart"
            "^lib/providers/{{}}.dart": "lib/providers/generated/{{}}.g.dart"
            "^lib/services/{{}}.dart": "lib/services/generated/{{}}.g.dart"

      idtruster|route_explorer:
        enabled: true
        generate_for:
          - lib/core/router/app_router.dart

builders:
  route_explorer:
    import: "package:idtruster/features/route_explorer/generators/route_explorer_generator.dart"
    builder_factories: ["routeExplorerBuilder"]
    build_extensions:
      {
        "lib/core/router/app_router.dart":
          ["lib/features/route_explorer/generated/route_explorer.g.dart"],
      }
    auto_apply: root_package
    build_to: source
