targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/models/*.dart
            - lib/providers/*.dart
            - lib/services/*.dart
        options:
          build_extensions:
            "^lib/models/{{}}.dart": "lib/models/generated/{{}}.freezed.dart"
            "^lib/providers/{{}}.dart": "lib/providers/generated/{{}}.freezed.dart"
            "^lib/services/{{}}.dart": "lib/services/generated/{{}}.freezed.dart"

      json_serializable:
        generate_for:
          include:
            - lib/models/*.dart
            - lib/providers/*.dart
            - lib/services/*.dart
        options:
          field_rename: snake
          explicit_to_json: true
          include_if_null: true

      riverpod_generator:
        generate_for:
          include:
            - lib/providers/*.dart
        options:
          build_extensions:
            "^lib/providers/{{}}.dart": "lib/providers/generated/{{}}.g.dart"
          provider_name_suffix: "Provider"

      source_gen|combining_builder:
        options:
          build_extensions:
            "^lib/models/{{}}.dart": "lib/models/generated/{{}}.g.dart"
            "^lib/providers/{{}}.dart": "lib/providers/generated/{{}}.g.dart"
            "^lib/services/{{}}.dart": "lib/services/generated/{{}}.g.dart"
